### ISSUE TITLE
Sensible redis eviction policy and possible use of EXPIRE set

### ISSUE THREAD

**Issue by dylanjha** [bee-queue/bee-queue#101]
I have a question about a sensible redis eviction policy.

In the default configuration for bee-queue, completed jobs and failed jobs get saved. In an average deployment, if `maxmemory-policy` is set to `noeviction` (default on Heroku-Redis, I believe it's commonly the default). Then that means eventually after some amount of time redis will be out of memory because all the completed jobs are still in the database.

As a result when this happens, Redis will start throwing OOM errors and new jobs will not be queued.

Obviously, bee-queue cannot control the maxmemory-policy of the Redis deployment, but it could be a little more friendly to the different eviction policies Redis has to offer.

Questions:

1. `allkeys-lru` - is this a sensible policy? The way bee-queue works, will this reliably remove completed jobs to make way for newly queued jobs? It seems like this might not work well because delayed jobs (with `delayUntil`) are at risk of being removed if they are older than the completed jobs
1. `volatile-lru` or `volatile-ttl`- this seems like it would work well, but it requires keys to have an expire set
1. Would it make sense to set an EXPIRE set on keys after a job succeeds or fails? This way, the `volatile-*` configurations can be leveraged

In an ideal configuration, I think it would be nice to keep completed jobs for as long as possible, and then remove them as needed to make way for new queued jobs. This allows the developer to have some visibility into how many jobs are being processed in each queue, while also making sure new jobs don't fail to be queued.

**Comment by LewisJEllis** [comment]
In general, I don't think any of Redis's built-in top-level-key-based eviction policies will interact well with bee-queue because bee-queue just used a constant set of keys. Instead of using a new key for each job, we store all job data for a queue together in a single hash. The [Under the hood](https://github.com/bee-queue/bee-queue#under-the-hood) docs section details the redis usage/layout; basically all of our keys are used frequently under normal operation, so I would imagine that the allkeys-lru eviction policy would either never touch anything or would just occasionally empty out the rare failed job id from the `bq:name:failed` set.

I created the [`removeOnSuccess` setting](https://github.com/bee-queue/bee-queue#settings) for this ever-growing-memory-usage concern, though - would it satisfy your need? You could also do a sort of manual "cleaning out the gutters" by removing job ids from the succeeded set and removing their data from the job data hash, but we don't have an easy built in helper for doing that after-the-fact.

I haven't given much thought to trying to lean on Redis's eviction policies, just because people might use all sorts of redis confs and may or may not be able to change them; I don't want to require config changes to use bee-queue. I remember considering implementing something on top of Redis keyspace events a while back, but decided against it for the same reason.

I agree it would be nice to keep completed jobs for as long as possible instead of deleting them right after completion to clear space, but I haven't seen an actual motivating use case that would benefit and haven't come up with a good way to make that happen completely automatically. A good approximation could be a periodically-run clean-out-the-gutters, but I prefer to use/require periodic scripts only for the most necessary things (like `checkStalledJobs` guaranteeing jobs still finish in the face of worker failures) and we still ultimately leave it to the user to decide how/when to run that periodic script.

**Comment by dylanjha** [comment]
>  basically all of our keys are used frequently under normal operation

Thank you for this, I did not realize this detail.

> I created the removeOnSuccess setting for this ever-growing-memory-usage concern

Yes, I am using this and it solves the issue.

> because people might use all sorts of redis confs and may or may not be able to change them

> I agree it would be nice to keep completed jobs for as long as possible instead of deleting them right after completion to clear space, but I haven't seen an actual motivating use case that would benefit and haven't come up with a good way to make that happen completely automatically

Fair enough. Thanks for giving it some thought.

-----

For now, I think `removeOnSuccess` is a fine solution while the alternative that I am recommending is more of a "nice to have".
