### ISSUE TITLE
MaxListenersExceededWarning for 'error' and 'ready' listeners

### ISSUE THREAD

**Issue by dylanjha** [bee-queue/bee-queue#102]
When creating 11 producer queues with the following configuration I'm seeing the MaxListenersExceededWarning  in node 8.9.1.

> (node:25043) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
> (node:25043) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ready listeners added. Use emitter.setMaxListeners() to increase limit
> (node:25043) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit

These queues are only meant to be producer queues, to push new jobs into the queue, not worker queues, so the overhead should be minimized.

I _think_ this happens because of two things:

1. the `Queue` class is a subclass of `Emitter` https://github.com/bee-queue/bee-queue/blob/master/lib/queue.js#L13
1. somewhere in the `Queue` instantiation process bee-queue is attaching event handlers to the 'ready' and 'error' events.

Things I can't figure out:

1. Where is number 2 happening?
1. Is `Queue` correctly removing event handlers when necessary
1. Is this a warning that is expected to show up?

It seems reasonable that on a webserver a user of bee-queue would want to instantiate > 10 producer queues. In this reasonable usage of the library I would not expect to get a node warning.

```javascript
const Redis = require('redis')
const Queue = require('bee-queue')
const redis = Redis.createClient('redis://localhost:6379')

const sharedConfig = {
  redis,
  getEvents: false,
  isWorker: false
}

const queueNames = ['queue-1', 'queue-2', 'queue-3',  'queue-4', 'queue-5', 'queue-6', 'queue-7', 'queque-8', 'queue-9', 'queue-10', 'queue-11']
queueNames.forEach((queueName) => {
   const queue = new Queue(queueName, sharedConfig)
   console.log('queue created', queue.name)
})
```

<img width="1061" alt="image 2018-03-14 at 11 00 33 am" src="https://user-images.githubusercontent.com/764988/37421608-f07d2134-2776-11e8-9569-5ff77a7b888b.png">

**Comment by LewisJEllis** [comment]
Thanks for the complete code example, made it very easy to understand what's going on! Your suspicions are mostly accurate. Specifically, this is due to reuse of the redis connection and the emitter with lots of listeners in this case is the redis client. If you stop reusing the redis client, you should stop seeing these warnings (try it out for a sanity check), but of course we don't want to do that, so we have to convince ourselves it's okay to ignore this warning instead.

#### Answers:
1. Happening in two spots:
- https://github.com/bee-queue/bee-queue/blob/master/lib/queue.js#L70 - queues emit errors when their redis connections emit errors
- https://github.com/bee-queue/bee-queue/blob/master/lib/redis.js#L33 - in `makeClient`, we wait for the Redis connection to be "ready" before resolving the promise with the client. This uses [`waitOn` from promise-callbacks](https://github.com/mixmaxhq/promise-callbacks/blob/master/src/statics/waitOn.js).
2. I think so. The `waitOn` helper definitely does, and I don't think we need to worry about removing the error listeners from the Redis connection. `Queue.close()` could consider removing them, but as is I'm not sure if we need to or should. `Queue.close()` already closes the redis connection, so I imagine if `Queue.close` is called the Queue instance and the Redis connection are going to be on their way to the GC anyway. I think it's fine, but let me know if you think there's a scenario that could impact this.
3. The purpose of the warning is to help detect when a potentially unbounded number of listeners are being created over time. Here, we just create 1-2 per queue so as long as you have a fixed number of queues, I would not be concerned.

#### Recommendation:
I would do something like:
```js
redis.setMaxListeners(numberOfQueues);
```
or maybe `numberOfQueues + 2` or something, depending on how the timing of the `waitOn` listeners contributes to the peak count.

#### Things to maybe still think about:
- Adding a note about this to docs on redis connection reuse (I still need to merge your pull request! wanted to make a couple small edits, will find time soon)
- Should `Queue.close()` remove the error listener from the connection?

**Comment by dylanjha** [comment]
> if you stop reusing the redis client, you should stop seeing these warnings (try it out for a sanity check)

Sanity check, you are correct 👍 

> so I imagine if Queue.close is called the Queue instance and the Redis connection are going to be on their way to the GC anyway. I think it's fine, but let me know if you think there's a scenario that could impact this.

This sounds reasonable

> The purpose of the warning is to help detect when a potentially unbounded number of listeners are being created over time
> Here, we just create 1-2 per queue so as long as you have a fixed number of queues, I would not be concerned.

I thought as much, to potentially detect an unbounded number of listeners node's 10 threshold seems a little low. As long as the Queue is only creating listeners in the instantiation process and it isn't grossly over-creating listeners we should be all goody. Just want to double check that as jobs are `created()` into the queue instances we don't end up with more listeners

------

> recommendation: `redis.setMaxListeners(numberOfQueues)`

I think your recommendation is good, I tried that out and it silenced the warnings as expected.

> Should Queue.close() remove the error listener from the connection?

I would have to look more into the internals to provide a useful recommendation. My gut says "yes", b/c in general a library should be a good steward to the rest of the code and clean up after itself, but as you mentioned before, once the redis connection is closed this should all be getting garbage collected anyway (including the listeners) so this will likely make no impact and it definitely will make no impact on seeing the warning in the first place so it wouldn't fix this original issue I ran into.

----

> Adding a note about this to docs on redis connection reuse (I still need to merge your pull request! wanted to make a couple small edits, will find time soon)

It's probably worth documenting these kind of things. Let me know if I can help with the open PR :)
