### ISSUE TITLE
[Question] Retry Utility

### ISSUE THREAD

**Issue by metallurgix** [bee-queue/bee-queue#103]
I am trying to integrate Bee-Queue in my new project and have few questions regarding the retry function after a job failure.
Basically I want by job to be re-tried 5 times before it is marked as failed.

Here is the sample code for which I am using for my project:

File1.js
```
const Queue = require('bee-queue');
const queue = new Queue('task1',{isWorker:false});
queue.createJob({}).retries(5).save()
```

File2.js
```
const Queue = require('bee-queue');
const queue = new Queue('task1');
queue.process(async (job) => {
  try{
    //Some DB Functions
  }
  catch{
    return Promise.reject()
  }
});
```

The problem is, when the an error is encountered, the task state is set as 'failed' and is never being retried.

I would like a little advice on how to proceed with fixing this issue.

**Comment by LewisJEllis** [comment]
This actually runs a bit deeper than you might initially realize, so bear with me.

First, `File2.js` that you have provided is not a valid JavaScript program. `catch` **must** bind an identifier to the caught value - that is, `try {} catch {}` is not JavaScript, and `try {} catch () {}` is not JavaScript, but `try {} catch (e) {}` is.

Second, I would not recommend using `Promise.reject` without passing a `reason` argument. Much like one simply cannot `throw` without providing a value (ideally an `Error`) to be caught, a promise cannot `reject` without a`reason` (also ideally an `Error`). Calling `Promise.reject()` treats the `reason` as `undefined` and kind of corresponds to doing `throw undefined;` which is just silly. When throwing, always throw `Error`s, and when rejecting, always reject with `Error`s.

Third, note that you don't need to use try/catch with an `async` function like you are in this example. `f1` and `f2` behave in exactly the same way in the following example:
```js
async function f1() {
  try {
    throw new Error('hi');
  } catch (e) {
    return Promise.reject(e);
  }
}

async function f2() {
  throw new Error('hi');
}

async function run() {
  try {
    await f1();
  } catch (e) {
    console.log('e1', e);
  }
  try {
    await f2();
  } catch (e) {
    console.log('e2', e);
  }
}

run();
```

So, your example code could just be:
```js
queue.process(async (job) => {
  // Some DB Functions
});
```
and everything will work correctly. If you prefer to be super explicit about the try/catch rather than omitting it, then the following is the same:
```js
queue.process(async (job) => {
  try {
    // Some DB Functions
  } catch (e) {
    return Promise.reject(e);
  }
});
```
Note also that in this latter example, doing `return Promise.reject();` without a `reason` actually causes the job to **succeed** on its first try, not fail! Why?

Well, rejected promises with a `reason` value of `undefined` don't trip bee-queue's check for "did this job fail?" as it is currently implemented. It's a side effect of how the processor tries to treat promise-based handlers and callback-based handlers the same way. For promise-based handlers, it passes the promise result into a single function which is effectively the `done` callback for callback-based handler functions; that function checks for the presence of an `err` value (which here is the rejection `reason`) and determines accordingly whether the job was successfully completed. It notably does not differentiate whether the promise's `resolve` or `reject` handler was called and does not try to check whether the promise was fulfilled or rejected (which is actually impossible to do synchronously). Instead, it assumes that the `err` will be truthy if the job failed, since the callback-based handlers must call `done(err)` to fail the job.

We *could* change this behavior to fail a job if its promise-based handler rejects even with a `reason` value of `undefined`, but this is really more a symptom of supporting both a promise-based and a callback-based API. I'm going to open an issue about the more high-level path forward for that.

**Comment by metallurgix** [comment]
Thank you for the help Lewis. I will just go ahead and use Promise.reject(err) for now.
I am looking forward to bee-queue2.0
Closing this topic, since the question is resolved.
