### ISSUE TITLE
Job.save() returns but doesn't always save

### ISSUE THREAD

**Issue by jknisley** [bee-queue/bee-queue#116]
I have been unable to replicate this locally, but have experienced it quite ofter with Heroku Redis (on a Premium 0 plan). We have web dynos that queue jobs and worker dynos that process them. Web dynos respond with a job id and worker dynos store job results or errors for later retrieval. The default config for both dyno types is:
```
{
        getEvents: false,
        removeOnFailure: true,
        removeOnSuccess: true,
        sendEvents: false,
        storeJobs: false
}
```

When the web dynos create a job with `const job = await queue.createJob(data).setId(uuid).save();`, it  appears that the job doesn't always actually get saved in redis. I can log the job ids processed by the workers and can see that not all of the job ids created by `save()` actually get processed, and looking in redis (via cli and arena) I never see those job ids appear. In debugging the issue I added `const redisJob = await queue.getJob(uuid);` immediately after `save()` and noted that for the same job ids that the workers never process, `await queue.getJob(uuid)` resolves with null. When running locally this never seems to occur and everything works as expected. It appears though that it's possible for a job creation to fail, even though `save()` resolves with a job id matching the uuid I passed to `setId()`.

One additional note: I removed `storeJobs: false` from the config, and so far it appears that jobs are always successfully saved in redis, both locally and on Heroku. Based on the docs, my understanding was that since we don't need to listen for job events in our setup, I could safely set this to false.

**Comment by LewisJEllis** [comment]
Very interesting! Thanks for the report.

I am not immediately sure what might be causing this, and it doesn't sound like a strange usage or anything like that; I also just reviewed the key code paths in question and nothing seems off. But, it sounds like `storeJobs` is a pretty clear off/on failure switch here, so I'd think that has to be indicative of *something* - I just don't have a great idea *what*. I've deployed bee-queue on DigitalOcean, AWS, and RedisLabs and never experienced anything like this, but I haven't run it on Heroku (or talked to anyone who has). One other note is that I haven't extensively used custom job IDs; I don't think that would be the cause, but it *is* a possible difference.

A few questions that may have a chance of leading somewhere:
- Can you confirm that you're using bee-queue v1.2.2? \
- What's your version of Redis?
- Can you confirm that all callsites of `queue.createJob(data).setId(uuid).save()` are `await`ing the promise?
- When you say you aren't seeing a job ID appear in Redis, are you looking at a log of all operations performed on Redis or are you just inspecting state after the fact?
- Are you able to reproduce this issue using the built-in auto-incr IDs instead of custom uuids?
- Are you able to reproduce this when setting `isWorker: false` on the web dyno?
- If you have some fixed number of web dynos `n` and worker dynos `m`, are you able to observe an arbitrary number of these non-saving jobs, or does it seem like it might be a fixed quantity relative to `n` and `m`? How often do they occur?

**Comment by LewisJEllis** [comment]
One more - are you able to reproduce this with just a single web and single worker with a single queue each? It looks like Heroku's premium 0 Redis plan has a fairly low limit on connection count at 40, so I would want to make sure you're not bumping into that.

**Comment by jknisley** [comment]
> Can you confirm that you're using bee-queue v1.2.2?

yes, v1.2.2


> What's your version of Redis?

3.2.11


> Can you confirm that all callsites of queue.createJob(data).setId(uuid).save() are awaiting the promise?

yes, all job creation logic hits the same method with that await


> When you say you aren't seeing a job ID appear in Redis, are you looking at a log of all operations performed on Redis or are you just inspecting Redis state after the fact?

After the fact. I did toggle `removeOnFailure` and `removeOnFailure` back to true and observed that the unprocessed jobs didn't appear anywhere in the Arena interface.


> Are you able to reproduce this issue using the default auto-incr IDs instead of custom uuids?

I have not tried yet, but I'll attempt this early next week. We went to uuids to avoid collisions from auto-increment resets.


> Are you able to reproduce this when setting isWorker: false on the web dyno?

The web dynos all have `isWorker:false`. In our staging environment (where this was observed), we had 2 web dynos (`isWorker: false`) and 2 worker dynos (`isWorker: true`). When I replicated locally with the remote redis instance, I had the web app running with `isWorker: false` and two worker processes running with `isWorker: true`. I was also able to replicate it with just web app running with `isWorker: true` and no additional worker processes.


> If you have some fixed number of web dynos n and worker dynos m, are you able to observe an arbitrary number of these non-saving jobs, or does it seem like it might be a fixed quantity relative to n and m? How often do they occur?

In the local setup (a web non-worker with 2 worker processes), it appears to pretty consistently fail on every third job creation. The highest connection count that I observed in redis was only 16.

On another note, `storeJobs: false` may be a red herring. At the moment I'm not able to replicate the issue with either setting of that flag, so it's entirely possible that there were issues with the redis instance itself during the window which I noticed this behavior. Even still, I wonder if there's a way to ensure that `save()` rejects instead of resolves if there is a redis error. The failsafe that I added, while the issue was replicable, was to recurse the call to my createJob method if `await queue.getJob(job.id)` returned a null after the call to `await queue.createJob(data).setId(jobId).save()`. With logging in place at the time I could see that I was definitely hitting that condition and that the failure case was intermittent. The recursed call always passed on the next attempt, but then a few job creations later the same situation would arise.

If I'm able to consistently replicate I'll be sure to post additional details.

**Comment by b00tsy** [comment]
I'm experiencing that issue as well. I got one service creating jobs and one working on them. 
`queue.createJob(data).setId(messageHash).save((err, job) => {})` calls the save promise without error, but the message is never received by the worker...

I have two deployments and every time the same messages get lost on both deployments. On one deployment redis runs in the same docker-compose environment on the other deployment redis runs on docker as the only service on that machine... 

That's my configuration ```const queueConfig = {
  isWorker: false,
  getEvents: true,
  sendEvents: false,
  storeJobs: false,
  removeOnSuccess: false,
  removeOnFailure: false
}```

**Comment by skeggse** [comment]
Apologies for never driving this issue to resolution. It's been a number of years, and I imagine that the context for the original problem is now gone. If you're still having a problem, feel free to re-open or open a new issue!

I will say that we experienced some problems when running Redis 3.2 that entirely went away when we moved to Redis 3.6.
