### ISSUE TITLE
Question: Multiple Dokku instances with one Redis

### ISSUE THREAD

**Issue by sarbull** [bee-queue/bee-queue#135]
Q: If i have multiple instances on dokku that connects to one Redis, does this mean the bee-queue will treat all the jobs as a single queue?

So like, every job that comes from a dokku instance will be added in the same queue in Redis and treated in the order they arrive?

Please confirm.

Thank you,
Cezar Sirbu

**Comment by cesarvarela** [comment]
I would like to know the answer of this too.

**Comment by nonphp** [comment]
Hi. I've set up multiple servers to host my app that uses bee-queue. Every instance connects to same redis on another server and everything works ok but with a major performance implication.
I think the implication is that every job has to be transfered over network and bee-queue uses lua scripting. It will be a lot faster if every server had its own redis running locally.
But in that case jobs have to be distributed evenly across queues – each client would connect to every redis instance that there is and use a hashing algorithm (similar to dynamo) to assign each job a token to decide which queue to use. Token is a number from 1 to 255 that is computed from hash value of job payload. Each queue has a token range (1-32, 32-64, etc.) and after token is computed we know which queue to use for this job.
I will write and open source a module to do this in several days. That is until bee-queue 2.0 comes with ioredis and redis cluster support.
Or if someone knows if there is a solution for that already please let me know.

**Comment by nonphp** [comment]
I'm finished my package. Haven't done any tests yet but it seems to have worked for me.

https://yarnpkg.com/en/package/bee-queue-dynamic

**Comment by skeggse** [comment]
Could you explain what a Dokku instance is?

**Comment by hughsw** [comment]
Dokku is one framework for scaling up applications to run on multiple hosts.

The Redis sharding that @yura415 posted is implemented at the client level, very straightforward if you want to roll your own such scaling.

I believe this Issue is about Bee-Queue having native support for effectively using multiple Redis servers (outside of a Redis cluster base).  Extending @yura415's comments, by doing this with ioredis and its native cluster support bee-queue will avoid reinventing the low-level infrastructure...
