### ISSUE TITLE
Get job data from pubsub event

### ISSUE THREAD

**Issue by tamlyn** [bee-queue/bee-queue#15]
My use case is that I want to send a message to the user over websockets when a job completes. The job data contains the user ID which I need to determine which socket to send the message on. However the `job succeeded` event only receives the job ID. 

Options:
1. Use `Queue.prototype.getJob` but as the docs point out that leaves a reference to the job on the queue instance which never gets removed.
2. Use `Job.fromId` directly (is that considered a public method?).
3. Add a `Queue.prototype.getJobData` method which doesn't add any references on the queue.
4. Add a `Queue.prototype.forgetJob` to remove reference.
5. Don't use bee-queue `job *` events and propagate events some other way.

Any thoughts? Happy to have a crack at implementing options 3 or 4 if either seems sensible.

**Comment by LewisJEllis** [comment]
Queue-level `job succeeded` and job-level `succeeded` events also receive a `result` parameter:
```javascript
queue.on('job succeeded', function (jobId, result) {
  console.log('Job ' + job.id + ' succeeded with result: ' + result);
});
```
This parameter is passed by the handler function to the `done` callback (i.e. `done(null, result)`).

Take a look at the [job succeeded](https://github.com/LewisJEllis/bee-queue#job-succeeded) and [handler](https://github.com/LewisJEllis/bee-queue#queueprototypeprocessconcurrency-handlerjob-done) bits - I think you should be able to use this to pass your user ID.

**Comment by tamlyn** [comment]
Yeah that's what I started out with but that doesn't work for errors as it's not practical to always include the user ID in any exception thrown. (Sorry I should have specified that I need to notify of job failures too.)

**Comment by LewisJEllis** [comment]
Ah, okay.

Since you're using queue-level events, I assume the process trying to send a websocket response won't always have a reference to the job we're reporting on. If that's not the case, or if that's a flexible situation, you might try to just use job-level events. Otherwise, laying out the options:

1, 4 - Yes, that could work, but as you've identified, that would be exactly the circumstance the docs are trying to warn against. I don't think I'm a fan of `forgetJob` because misuse could result in job events never propagating and thus odd system states, and I generally would prefer to have the queue/library handle job life cycle rather than make the user worry about it.
2 - No, I wouldn't consider that public. It's undocumented, and the only way you'd get to it is with something silly like `var Job = queue.createJob().prototype; Job.fromId(...)`. 
5 - seems hard, let's make this easy
3 - seems narrow, but nothing wrong with it. A bit of overlap with my first idea below.

The two solutions I'm thinking about right now are:
1) Right now, `getEvents` entirely enables/disables queue-level and job-level pubsub events. If `getEvents` is false, `getJob` does not add any reference to the queue object in order to emit events, but you also don't get queue-level pubsub events. If you're only using queue-level pubsub events (and not job-level), you might want to use `getJob` without saving the reference to that job object, and this ought to be possible (but currently isn't). Downside: your use case will always need an extra round trip to redis, to go find the job after receiving the queue-level pubsub event.

2) Just send `job.data` back with the pubsub messages, so the signature could become
```javascript
queue.on('job succeeded', function (job, result) {
  console.log('Job ' + job.id + ' succeeded with result ' + result + ' and data ' + job.data);
});
```
Code-wise this is an easy change, but the downside is it could add a lot of network/redis overhead depending on how large the job data is. I think for that reason, if we go this route, we would want to put it behind a boolean option flag to save the overhead when it's unneeded, but then we have a sort of inconsistency between the two modes of what the `job succeeded` handler's signature should be. I think we could change it to always be `queue.on('job succeeded', function (job, result) {` and just not populate `job.data` if that flag is disabled.

Personally, I'm leaning toward #2, as it'll best fit your use case, seems like a fairly reasonable change, and can just be disabled by default and enabled by those who need it. I'm not too worried about the signature change since 1.0.0 is in the pipeline anyway. Let me know what you think.

**Comment by tamlyn** [comment]
Your second option sounds perfect.

**Comment by LewisJEllis** [comment]
Great. If you need it ASAP, I'm happy to review a PR any time, but otherwise I can put this together over the weekend or early next week.

**Comment by tamlyn** [comment]
Turns out I need to have a pubsub event bus for other stuff in the app so I'm using that to send back info from job events. So I don't imminently need this change. But it still seems like a sensible addition.

**Comment by matteocontrini** [comment]
Looking forward to this as well :)
The second solution seems a good idea!

**Comment by LewisJEllis** [comment]
I forgot about this for a while since tamlyn found a workaround, but I agree that option 2 is useful and should be done.
