### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by tnolet** [bee-queue/bee-queue#157]
Hey, short question. I'm considering Bull or Bee-queue. Bee seems to do all I want, but I'm a bit scared of by the open issues and the lack of activity. Is Bee still maintained?

**Comment by archae0pteryx** [comment]
I second this question.

**Comment by tnolet** [comment]
@archae0pteryx I'm pretty sure after 19 days of silence that this repo is probably dead. I'm using Bull for now.

**Comment by bradvogel** [comment]
We (at Mixmax) are still using Bee Queue to process hundreds of millions of jobs a day, and it's working well for us. We still watch github issues in this repo and fix major flaws that affect us, though there haven't been any since Bee Queue 1.0. We unfortunately don't have bandwidth to answer questions or respond to feature requests.

We haven't tested Bull in quite a while, so they might have fixed the performance and data consistency bugs. Bull will likely remain the more full-featured queue while Bee Queue will be the minimal version that favors performance and consistency.

**Comment by tnolet** [comment]
@bradvogel thanks for jumping Brad. I will have a close look at my needs. I'm not using many of the Bull features, so Bee would still be a good fit.

**Comment by shadowbrush** [comment]
@tnolet Did you go Bull or Bee? Any insights a few months after adoption? Thanks!

**Comment by tnolet** [comment]
@shadowbrush I went for Bee actually. Has been rock solid I'm happy to report. Doing 20M+ of messages a month and growing.

**Comment by shadowbrush** [comment]
Thank you, @tnolet, good to know. Still on the fence, myself. Checkly looks interesting, too. Need support for GraphQL. :)

**Comment by tnolet** [comment]
@shadowbrush Checkly supports GraphQL!

**Comment by shadowbrush** [comment]
@tnolet That's good go know, thanks. Will evaluate to monitor our API.
