### ISSUE TITLE
Replace node_redis with ioredis

### ISSUE THREAD

**Issue by thelinuxlich** [bee-queue/bee-queue#16]
For redis 3 cluster support

**Comment by LewisJEllis** [comment]
I've had my eye on ioredis and will give this some consideration. When I started on this library it hadn't been released yet, but now it's looking quite nice.

**Comment by thelinuxlich** [comment]
I forked bee-queue to add ioredis and only two tests are failing(reconnection)

**Comment by LewisJEllis** [comment]
Cool! Off the top of my head, I would expect those two tests to fail among all others; they're pretty specific to how node_redis deals with connections. I made an ioredis branch; feel free to open a PR to it and we can work from there.

**Comment by thelinuxlich** [comment]
Actually there were a lot of tests failing and now there are only two: Queue "after each" hook and Queue Health Check reports a failed job

My fork https://github.com/thelinuxlich/bee-queue/commit/795a465ac4fa047c3ed0b8ba831129c45bb84288

**Comment by LewisJEllis** [comment]
Moving forward with this in #21. I just want to leave a note here on cluster support in general; 

Because of the nature of Redis and its lists and (mostly) its Lua scripting, bee-queue won't exactly be able to offer true cluster support. It will work on Redis cluster deployments, but it will really just run everything on one Redis instance. Otherwise, the Lua scripts won't be able to access all the keys they need to in one place.

Fortunately [Redis cluster]() has a very nice way to do this:

> Redis Cluster supports multiple key operations as long as all the keys involved into a single command execution (or whole transaction, or Lua script execution) all belong to the same hash slot. The user can force multiple keys to be part of the same hash slot by using a concept called hash tags.
>
> Hash tags are documented in the Redis Cluster specification, but the gist is that if there is a substring between {} brackets in a key, only what is inside the string is hashed, so for example this{foo}key and another{foo}key are guaranteed to be in the same hash slot, and can be used together in a command with multiple keys as arguments.

but it should be clear that any one instance of bee-queue will still be running entirely on one instance of Redis. Of course, it will be possible to run multiple instances of bee-queue on multiple instances of Redis.

**Comment by hustcer** [comment]
+1
need a update on this, asap. Thanks.

**Comment by skeggse** [comment]
From #21 
>What's the latest on `ioredis` vs `redis`? It sounds like the two are on a long-term collision course, and that performance is comparable, but I'm not certain. I don't have a strong opinion one way or the other, but this PR would definitely need to be updated for `1.0.0`. Feel free to reopen if you think this is still worthwhile.
