### ISSUE TITLE
Process only one job at a time from multiple process

### ISSUE THREAD

**Issue by s888** [bee-queue/bee-queue#188]
Hi,
I am new to this module and I am trying it out.

But it is not working as I am expecting it to.

sender.ts
```
const Queue = require('bee-queue');
const addQueue = new Queue('addition');

const job = addQueue.createJob({x: 2, y: 3});
job
  .timeout(3000)
  .retries(2)
  .save()
  .then((job) => {
    // job enqueued, job.id populated
  });
```

receiver.ts
```
const Queue = require('bee-queue');
const addQueue = new Queue('addition');
setTimeout(function(){
      addQueue.process(1,function (job, done) {
        console.log(`Processing job ${job.id}`);
        //return done(null, job.data.x + job.data.y);
      });
},5000)
```
receiver.ts  keeps on printing all the jobs in loop. 
```
Processing job 15
Processing job 15
Processing job 15 
```
And after I restart receiver.ts I cannot get the messages. Even though I have not called done()

My requirement is I have multiple workers that will pick jobs from this queue one at a time. No two workers will pick the same job. Only after their respective task is complete they will remove the job from the queue. Can I accomplish this using this module?

Can someone please explain this to me.

**Comment by s888** [comment]
Is it because of the timeout parameter.
Setting timeout(0) does not delete the message. But why does the messages keep on printing?

**Comment by hughsw** [comment]
You can accomplish what you want.

You are not calling `done()`, so each time your process function is called, Bee-Queue waits 3000 msec and then kills the job.  It retries two times, for a total of three tries.  After the third timeout the job is failed.  That's why restarting the receiver doesn't fix things.

If you uncomment your call to `done()` things work the way you want.

At a minimum you should add a `job.on('succeeded', cb)` to your sender so that it is notified of the success and gets the result.  E..g
```javascript
job.on('succeeded', result => {
  console.log('succeeded: result:', result);
});
```

**Comment by skeggse** [comment]
Closing as this seems to be usage-related. If there is a bug, feel free to reopen!
