### ISSUE TITLE
Job set as failed when it shouldn't

### ISSUE THREAD

**Issue by matteocontrini** [bee-queue/bee-queue#37]
I put an application with bee-queue in production yesterday. Two workers have to handle approximately 2k jobs (total) every 20 minutes.

I now find that there are about 50 jobs marked as "failed". When is a job supposed to be "fail". I **never** call done() with an error.

Thanks.

**Comment by matteocontrini** [comment]
How can I clear failed jobs? Unfortunately I don't know much about Redis commands.

**Comment by LewisJEllis** [comment]
Sorry for the delay here; I sort of drowned in my GitHub notifications for a while.

I've never experienced what you're describing, although my deployments see load in occasional spikes rather than sustained regular volume. Though I would hope that doesn't make any difference, it's possible that your use case has something to it that I'm missing or failed to consider. Can you post a minimal reproduction, or describe your worker handlers in more detail? As far as I'm able to imagine, the only way you would end up with a failed job is if the handler throws an exception (if `catchExceptions` is enabled) or calls `done` with an `err` parameter, but it sounds like neither of those should be the case.

50 failed jobs won't take up much space, but an easy method for getting rid of them sounds like a useful thing to implement & expose, come to think of it. If this is still helpful, you can clear a failed job by doing an [SREM](http://redis.io/commands/srem) on `bq:<name>:failed` and an [HDEL](http://redis.io/commands/hdel) on `bq:<name>:jobs`, each with the job ID as a parameter. To get all of the failed jobs for iteration, you can use [SMEMBERS](http://redis.io/commands/smembers) with `bq:<name>:failed`. The [under the hood](https://github.com/LewisJEllis/bee-queue#under-the-hood) section has some more reference on Bee-Queue's use of/layout in Redis.

**Comment by matteocontrini** [comment]
Now that I thought about that, what happens when a timeout occurs? Will the job be set as failed? That could actually be the reason of these failing jobs with apparently no reason.

In that case, there's no bug fortunately :)
It would be just an improvement for better jobs handling when they fail.

**Comment by skeggse** [comment]
Yep, a job timeout will cause the job to fail, and trigger retry behavior if configured.
