### ISSUE TITLE
BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE

### ISSUE THREAD

**Issue by domchik** [bee-queue/bee-queue#448]
Hello, I am getting this error from redis when calling  job.save() :

 `BUSY Redis is busy running a script. You can only call SCRIPT KILL or SHUTDOWN NOSAVE`

this happens when the traffic is very heavy. bee-queue is the only one that uses redis in our application. 

any suggestions what may cause this error and how it can be avoided?

thanks a lot

**Comment by jschapiro003** [comment]
+1

**Comment by shils** [comment]
This error is caused by a long running server-side lua script. As bee-queue is the only thing that uses redis, this script must be one of the scripts that bee-queue uses to manage queue state. The most likely culprits are [raiseDelayedJobs](https://github.com/bee-queue/bee-queue/blob/master/lib/lua/raiseDelayedJobs.lua) or [checkStalledJobs](https://github.com/bee-queue/bee-queue/blob/master/lib/lua/checkStalledJobs.lua) as the others scale sub-linearly in time with respect to the number of jobs in the queue.
