### ISSUE TITLE
Group concurrency for one queue

### ISSUE THREAD

**Issue by cuifan53** [bee-queue/bee-queue#573]
First thanks for this library, it works well in my project! Now i have a problem hope to get help:

Suppose I have 5 clients and get 20 pieces of data for each one. The data of different clients can be processed at the same time, but for the same client must be processed in order. My current approach is to put these 100 pieces of data into a queue and the concurrency number during processing is 1, so I am trying to improve performance. If I just increase the concurrency number, then I cannot guarantee the order of processing the data of the same client . It is also difficult to create a queue for every client, because the number of client changes frequently.

Do you have any good idea? Thanks very much!

**Comment by compwright** [comment]
@cuifan53 it's tough to know how to answer this without more information on what your jobs are doing and how the handlers are implemented, but I suspect the issue is not that the jobs are starting out of order but rather are finishing out of order, due to differences is computation time or resource access within your job handler.

> It is also difficult to create a queue for every client, because the number of client changes frequently.

I disagree, it is perfectly acceptable and reasonable to create a queue for each client. Redis can handle a large number of queues, and bee-queue will delete the Redis keys that hold queues when no jobs are left.

**Comment by cuifan53** [comment]
@compwright Thanks, you're right, I'll try to create a queue for each client.
