### ISSUE TITLE
Cron jobs?

### ISSUE THREAD

**Issue by mcorner** [bee-queue/bee-queue#81]
Is there a suggested way to do cron like jobs with bee-queue?  This exists in bull and we are trying to pick a queuing system.  Three things I have thought of:

- use cron on one node to schedule jobs.  This should work, but makes a single point of failure and some configuration pains.

- use AWS lambda and cloudwatch scheduled events to queue jobs.  No single point of failure, but introduces another tool.

- run an initial adding of jobs, each of which reschedule themselves in the future, but this sounds very fragile and hard to start.  There is a lot to not like here...

Any suggestions would be appreciated.

**Comment by bradvogel** [comment]
We'd rather not add this feature since it'll complicate the codebase. Bee-queue is the "lite" version of Bull with a focus on 100% stability and performance.

There are packages out there such as `cron-cluster` to make it distributed so you don't have single point of failure. You can use them to enqueue a new bee-queue job on a schedule.

**Comment by LewisJEllis** [comment]
FWIW, I've used Lambda + cloudwatch timers for this sort of pattern before and found it pretty easy to get going. The serverless framework makes it pretty straightforward and even supports cron syntax: https://serverless.com/framework/docs/providers/aws/events/schedule/
